### ISSUE TITLE
Music playback issues

### ISSUE THREAD

**Issue by TheWhiteHunter** [paul-io/momo-discord#13]
Just a few things that myself and the members of my server have been noticing.

First thing is that songs will jump ahead by a second or two at random periodically.

Second thing is that songs will seem to speed up briefly.

**Comment by paul-io** [comment]
This has been plaguing me for a while, and I'm trying to find the culprit. I think I've made small steps towards a more stable experience. It's always on the radar

**Comment by paul-io** [comment]
This has been resolved in momo 2.0, which has been moved to a new repository: https://github.com/paul-io/momo-2
